<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * English language strings for local_homepage_config.
 *
 * @package    local_homepage_config
 * @copyright  2026 Carlos Costa
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

// Plugin identity
$string['pluginname']             = 'Homepage Configuration';
$string['homepage_config:manage'] = 'Manage homepage configuration';

// Admin menu labels
$string['settings']               = 'Homepage Visual Config';
$string['exportimport']           = 'Homepage Visual Config — Export / Import';
$string['pluginsettings']         = 'Homepage Visual Config — Settings';

// Summary panel (index.php)
$string['current_config']         = 'Current configuration';
$string['last_exported']          = 'Last exported: {$a}';
$string['last_imported']          = 'Last imported: {$a}';
$string['never']                  = 'never';
$string['settings_count']         = '{$a} theme settings (slider, tiles, banners, SCSS, colours…)';
$string['files_count']            = '{$a} uploaded files (slider images, logos, backgrounds…)';
$string['menus_count']            = '{$a} Smart Menu(s)';
$string['flavours_count']         = '{$a} Flavour(s)';
$string['blocks_count']           = '{$a} block(s) on site-index / course-index pages';

// Export
$string['export']                 = 'Export configuration';
$string['export_desc']            = 'Download the complete visual configuration as a ZIP file. Includes: Boost Union theme settings, uploaded images, Smart Menus, Flavours, and frontpage/course-index blocks.';
$string['export_btn']             = 'Download export (.zip)';

// Import
$string['import']                 = 'Import configuration';
$string['import_desc']            = 'Upload a ZIP exported from another Moodle 4.1 instance with this plugin. Theme caches are purged automatically after import.';
$string['import_file']            = 'Configuration file (.zip)';
$string['import_blocks']          = 'Restore blocks (site-index + course-index)';
$string['import_blocks_warn']     = 'Warning: this will delete and replace all existing blocks on the site frontpage and course category pages. Only import ZIP files exported by this plugin from a trusted Moodle instance — block configuration data is deserialized during restore.';
$string['import_btn']             = 'Import';

// Import result messages
$string['import_success']         = 'Import successful — {$a->settings} theme settings, {$a->core_settings} core settings, {$a->files} files.';
$string['import_success_menus']   = 'Smart Menus: {$a} menu(s) restored.';
$string['import_success_flavours']= 'Flavours: {$a} flavour(s) restored.';
$string['import_success_blocks']  = 'Blocks: {$a} block(s) restored.';
$string['import_errors']          = 'Import completed with {$a} error(s). See details below.';
$string['import_error_details']   = 'Import error details';

// Errors
$string['cannotopenzip']          = 'Cannot open the ZIP file. Make sure the file is a valid export.';
$string['invalidexportfile']      = 'Invalid export file: manifest not found. Use a file generated by this plugin.';
$string['ziparchive_missing']     = 'PHP ZipArchive extension is required but not available on this server.';
$string['incompatibleformatversion'] = 'This export was created with a newer version of the plugin (format {$a->got}). The maximum supported format is {$a->max}. Please upgrade the plugin before importing.';
$string['import_err_upload']      = 'File upload failed. Check PHP upload settings (upload_max_filesize, post_max_size).';
$string['import_err_extension']   = 'Invalid file type. Please select a .zip file exported by this plugin.';
$string['import_err_mimetype']    = 'The uploaded file does not appear to be a valid ZIP archive (detected type: {$a}).';

// ── Settings page ─────────────────────────────────────────────────────────────

// Section: Theme component
$string['heading_theme']          = 'Theme component';
$string['heading_theme_desc']     = 'The Moodle theme whose <code>config_plugins</code> entries and files will be exported / imported.';

$string['themecomponent']         = 'Theme component name';
$string['themecomponent_desc']    = 'Internal Moodle component identifier of the theme, e.g. <code>theme_boost_union</code>. Must match the component stored in the <code>config_plugins</code> table.';

// Section: Dedicated DB tables
$string['heading_tables']         = 'Dedicated theme tables';
$string['heading_tables_desc']    = 'Names of extra DB tables created by the theme. Leave blank to disable export of the corresponding feature.';

$string['tablemenus']             = 'Smart Menus table';
$string['tablemenus_desc']        = 'DB table that stores Smart Menu definitions (without the <code>mdl_</code> prefix).';

$string['tablemenuitems']         = 'Smart Menu items table';
$string['tablemenuitems_desc']    = 'DB table that stores Smart Menu item definitions (without the <code>mdl_</code> prefix).';

$string['tableflavours']          = 'Flavours table';
$string['tableflavours_desc']     = 'DB table that stores Flavour (visual variant) definitions (without the <code>mdl_</code> prefix).';

// Section: Advanced
$string['heading_advanced']       = 'Advanced';
$string['heading_advanced_desc']  = 'Fine-tune which files, blocks, and core settings are included in the export.';

$string['flavourfileareas']       = 'Flavour file areas';
$string['flavourfileareas_desc']  = 'File areas whose <code>itemid</code> is a flavour row ID. One per line. These are handled separately so that file IDs are remapped correctly on import.';

$string['blockpagetypes']         = 'Block page type prefixes';
$string['blockpagetypes_desc']    = 'Page type prefixes used to select which block instances to export. One per line. A <code>%</code> wildcard is appended automatically, e.g. <code>course-index</code> also captures <code>course-index-category-5</code>.';

$string['coreconfigkeys']         = 'Core config keys';
$string['coreconfigkeys_desc']    = 'Keys from the core Moodle <code>config</code> table (no plugin) to include in the export. One per line. Only these specific keys will ever be written on import.';

// Section: Dynamic tiles
$string['heading_tiles']      = 'Dynamic front-page tiles';
$string['heading_tiles_desc'] = 'Configure the stat tiles injected into <code>&lt;div id="hpc-tiles"&gt;&lt;/div&gt;</code> on the site front page. Live course/user counts are computed on every page load.';
$string['tilescfg']           = 'Tiles configuration (JSON)';
$string['tilescfg_desc']      = 'JSON array of tile objects. Each object supports: <code>title</code>, <code>subtitle</code>, <code>type</code> (courses/users/custom/none), <code>catid</code>, <code>subcats</code>, <code>value</code> (custom), <code>icon</code> (FA name), <code>color</code> (blue/green/orange/purple/red/teal), <code>link</code>, <code>newtab</code>.<br>Example: <pre>[{"title":"Networks","type":"courses","catid":3,"subcats":true,"icon":"sitemap","color":"orange","link":"/course/index.php?categoryid=3"}]</pre>';

// Events
$string['event_config_exported']  = 'Homepage configuration exported';
$string['event_config_imported']  = 'Homepage configuration imported';

// Privacy
$string['privacy:metadata']       = 'This plugin does not store any personal data. It reads and writes Moodle site configuration only.';
